@iot_backend_HostAddress = https://localhost:7000

GET {{iot_backend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{iot_backend_HostAddress}}/api/dashboard/GetAllSwitchHistories

###

GET {{iot_backend_HostAddress}}/api/dashboard

###
